# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
    - $HOME/.m2

#https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied
before_install:
  - chmod +x gradlew

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
    - master

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
#notifications:
#  email: false